import './parse.js'
import './compile.js'
import './sourcemap.js'
import './print.js'
import './watr.js'
import './polyfill.js'
import './optimize.js'
import './stringref.js'
import './rounding-mode.js'
import './half-precision.js'
import './acquire-release.js'
import './js-string-builtins.js'
// official spec testsuite runs separately: npm run test:spec
// import './bench.js'
