import './parse.js'
import './compile.js'
import './print.js'
import './watr.js'
import './polyfill.js'
import './optimize.js'
import './stringref.js'
import './rounding-mode.js'
import './js-string-builtins.js'
import './testsuite.js'
// import './bench.js'
