import t, { is, ok, same, throws } from 'tst'
import { file } from './util.js'

// Feature detection for experimental WASM features
// Must actually compile WASM to detect runtime support (not just API existence)
const hasExceptionHandling = (() => {
  try {
    // Simple module with exnref type: (module (type (func)) (tag (type 0)))
    new WebAssembly.Module(new Uint8Array([
      0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
      0x01, 0x04, 0x01, 0x60, 0x00, 0x00,             // type section: (func)
      0x0d, 0x03, 0x01, 0x00, 0x00                    // tag section: tag using type 0
    ]))
    return true
  } catch { return false }
})()
const hasWideArithmetic = (() => {
  try {
    // i64.add128 requires wide arithmetic support
    new WebAssembly.Module(new Uint8Array([0,97,115,109,1,0,0,0,1,9,1,96,4,126,126,126,126,2,126,126,3,2,1,0,10,9,1,7,0,32,0,32,1,32,2,32,3,252,19,11]))
    return true
  } catch { return false }
})()

// Conditional test runner: use todo() if feature missing, mute() if supported
const ifExn = hasExceptionHandling ? t.mute : t.todo
const ifWide = hasWideArithmetic ? t.mute : t.todo

// Create a WASM-exported table64 for testing, since JS WebAssembly.Table with index:'i64'
// doesn't create a true i64-indexed table in current Node versions
const createTable64 = () => {
  try {
    // Binary for: (module (table i64 10 20 funcref) (export "table64" (table 0)))
    const bytes = new Uint8Array([
      0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
      0x04, 0x05, 0x01, 0x70, 0x05, 0x0a, 0x14,       // table section: funcref, flag=0x05 (i64+max), min=10, max=20
      0x07, 0x0b, 0x01, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x36, 0x34, 0x01, 0x00 // export "table64" table 0
    ])
    const mod = new WebAssembly.Module(bytes)
    const inst = new WebAssembly.Instance(mod)
    return inst.exports.table64
  } catch (e) {
    // Fallback to regular table if table64 not supported
    return new WebAssembly.Table({ initial: 10, maximum: 20, element: 'anyfunc' })
  }
}

const spectest = {
  memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }),
  shared_memory: new WebAssembly.Memory({ initial: 1, maximum: 2, shared: true }),
  table: new WebAssembly.Table({ initial: 10, maximum: 20, element: 'anyfunc' }),
  // table64: new WebAssembly.Table({ initial: 10, maximum: 20, element: 'anyfunc', index: 'i64' }),
  table64: createTable64(),
  global_i32: 666,
  global_i64: 666n,
  global_f32: 666.6,
  global_f64: 666.6,
  print: console.log,
  print_i32: console.log,
  print_i64: console.log,
  print_f32: console.log,
  print_f64: console.log,
  print_i32_f32: console.log,
  print_f64_f64: console.log,
}

// Core tests
t.mute('/test/official/address.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/address0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/address1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/address64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/align.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/align0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/align64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/annotations.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/array_copy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/array_fill.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/array_init_data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/array_init_elem.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/array_new_data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/array_new_elem.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/array.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/binary_leb128_64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/binary-gc.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/binary-leb128.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/binary.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/binary0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/block.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_if.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_on_cast_fail.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_on_cast.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_on_non_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_on_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/bulk.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/bulk64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/call_indirect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/call_indirect64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/call_ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/call.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/comments.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/const.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/conversions.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/custom.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/data_drop0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/data0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/data1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/elem.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/endianness.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/endianness64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/exports.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/exports0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/extern.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f32_bitwise.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f32_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f32.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f64_bitwise.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f64_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/fac.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_exprs.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_exprs0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_exprs1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_literals.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_memory.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_memory0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_memory64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_misc.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/forward.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/func_ptrs.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/func.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/global.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i16x8_relaxed_q15mulr_s.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i31.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i32.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i32x4_relaxed_trunc.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i8x16_relaxed_swizzle.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/id.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/if.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/imports.wast', async function () { await file(this.name, { spectest: { ...spectest, memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }) } }) })
t.mute('/test/official/imports0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/imports1.wast', async function () { await file(this.name, { spectest: { ...spectest, memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }) } }) })
t.mute('/test/official/imports2.wast', async function () { await file(this.name, { spectest: { ...spectest, memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }) } }) })
t.mute('/test/official/imports3.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/imports4.wast', async function () { await file(this.name, { spectest: { ...spectest, memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }) } }) })
t.skip('/test/official/inline-module.wast', async function () { await file(this.name, { spectest }) })
t.skip('/test/official/instance.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/int_exprs.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/int_literals.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/labels.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/left-to-right.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/linking.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/linking0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/linking1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/linking2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/linking3.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/load.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/load0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/load1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/load2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/load64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/local_get.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/local_init.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/local_set.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/local_tee.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/loop.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_copy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_copy0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_copy1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_copy64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_fill.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_fill0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_fill64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_grow.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_grow64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_init.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_init0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_init64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_redundancy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_redundancy64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_size_import.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_size.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_size0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_size1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_size2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_size3.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_trap.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_trap0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_trap1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_trap64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory-multi.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory64-imports.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/names.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/nop.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/obsolete-keywords.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_as_non_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_cast.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_eq.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_func.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_is_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_test.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/relaxed_dot_product.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/relaxed_laneselect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/relaxed_madd_nmadd.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/relaxed_min_max.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/return_call_indirect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/return_call_ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/return_call.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/return.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/select.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_address.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_align.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_bit_shift.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_bitwise.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_boolean.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_const.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_conversions.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_pmin_pmax.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_rounding.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_pmin_pmax.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_rounding.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_arith2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_extadd_pairwise_i8x16.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_extmul_i8x16.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_q15mulr_sat_s.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_sat_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_arith2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_dot_i16x8.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_extadd_pairwise_i16x8.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_extmul_i16x8.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_trunc_sat_f32x4.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_trunc_sat_f64x2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_arith2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_extmul_i32x4.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i8x16_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i8x16_arith2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i8x16_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i8x16_sat_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_int_to_int_extend.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_linking.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load_extend.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load_splat.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load_zero.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load8_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load16_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load32_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load64_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_memory-multi.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_select.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_splat.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store8_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store16_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store32_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store64_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/skip-stack-guard-page.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/stack.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/start.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/start0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/store.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/store0.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/store1.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/store2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/struct.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/switch.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_copy_mixed.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_copy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_copy64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_fill.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_fill64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_get.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_get64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_grow.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_grow64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_init.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_init64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_set.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_set64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_size.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_size64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table-sub.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table64.wast', async function () { await file(this.name, { spectest }) })
ifExn('/test/official/tag.wast', async function () { await file(this.name, { spectest }) })
ifExn('/test/official/throw_ref.wast', async function () { await file(this.name, { spectest }) })
ifExn('/test/official/throw.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/token.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/traps.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/traps0.wast', async function () { await file(this.name, { spectest }) })
ifExn('/test/official/try_table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/type-canon.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/type-equivalence.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/type-rec.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/type-subtyping.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/type.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unreachable.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unreached-invalid.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unreached-valid.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unwind.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-custom-section-id.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-import-field.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-import-module.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-invalid-encoding.wast', async function () { await file(this.name, { spectest }) })

// Proposals - custom-page-sizes
t.todo('/test/official/proposals/custom-page-sizes/custom-page-sizes-invalid.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/custom-page-sizes/custom-page-sizes.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/custom-page-sizes/memory_max.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/custom-page-sizes/memory_max_i64.wast', async function () { await file(this.name, { spectest }) })

// Proposals - threads
t.mute('/test/official/proposals/threads/atomic.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/threads/exports.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/threads/imports.wast', async function () { await file(this.name, { spectest: { ...spectest, memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }) } }) })
t.mute('/test/official/proposals/threads/memory.wast', async function () { await file(this.name, { spectest }) })

// Proposals - wide-arithmetic
ifWide('/test/official/proposals/wide-arithmetic/wide-arithmetic.wast', async function () { await file(this.name, { spectest }) })
