import t, { is, ok, same, throws } from 'tst'
import { file } from './index.js'

const spectest = {
  memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }),
  table: new WebAssembly.Table({ initial: 10, maximum: 20, element: 'anyfunc' }),
  global_i32: 666,
  global_i64: 666n,
  global_f32: 666.6,
  global_f64: 666.6,
  print: console.log,
  print_i32: console.log,
  print_i64: console.log,
  print_f32: console.log,
  print_f64: console.log,
  print_i32_f32: console.log,
  print_f64_f64: console.log,
}

t.mute('/test/official/address.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/align.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/binary-leb128.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/binary.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/block.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_if.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br_table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/br.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/bulk.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/call_indirect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/call.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/comments.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/const.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/conversions.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/custom.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/elem.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/endianness.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/exports.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f32_bitwise.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f32_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f32.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f64_bitwise.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f64_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/f64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/fac.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_exprs.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/float_literals.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_memory.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/float_misc.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/forward.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/func_ptrs.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/func.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/global.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i32.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/i64.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/if.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/imports.wast', async function () { await file(this.name, { spectest: { ...spectest, memory: new WebAssembly.Memory({ initial: 1, maximum: 2 }) } }) })
t.mute('/test/official/inline-module.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/int_exprs.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/int_literals.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/labels.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/left-to-right.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/linking.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/load.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/local_get.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/local_set.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/loop.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_copy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_fill.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_grow.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_init.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_redundancy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_size.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory_trap.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/memory.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/names.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/nop.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/obsolete-keywords.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_func.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_is_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/ref_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/return.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/select.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_address.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_align.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_bit_shift.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_bitwise.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_boolean.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_const.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_conversions.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_pmin_pmax.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4_rounding.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f32x4.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_pmin_pmax.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2_rounding.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_f64x2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_arith2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_extadd_pairwise_i8x16.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_extmul_i8x16.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_q15mulr_sat_s.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i16x8_sat_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_arith2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_dot_i16x8.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_extadd_pairwise_i16x8.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_extmul_i16x8.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_trunc_sat_f32x4.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i32x4_trunc_sat_f64x2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_arith.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_arith2.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_cmp.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_i64x2_extmul_i32x4.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_int_to_int_extend.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_linking.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load_extend.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load_splat.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load_zero.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load8_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load16_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load32_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_load64_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_splat.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store8_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store16_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store32_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/simd_store64_lane.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/skip-stack-guard-page.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/stack.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/start.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/store.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/switch.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_copy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_fill.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_get.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_grow.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_init.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_set.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table_size.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table-sub.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/token.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/traps.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/type.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unreachable.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unreached-invalid.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unreached-valid.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/unwind.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-custom-section-id.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-import-field.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-import-module.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/utf8-invalid-encoding.wast', async function () { await file(this.name, { spectest }) })


// extensions
t.todo('/test/official/proposals/exception-handling/exports.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/exception-handling/imports.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/exception-handling/ref_null.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/exception-handling/tag.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/exception-handling/throw_ref.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/exception-handling/throw.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/exception-handling/try_table.wast', async function () { await file(this.name, { spectest }) })

t.mute('/test/official/proposals/extended-const/data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/extended-const/elem.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/extended-const/global.wast', async function () { await file(this.name, { spectest }) })

t.mute('/test/official/proposals/function-references/binary.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/br_on_non_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/br_table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/call_ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/elem.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/func.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/global.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/if.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/linking.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/local_get.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/local_init.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/ref_as_non_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/ref_is_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/ref_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/return_call_indirect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/return_call_ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/return_call.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/select.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/table-sub.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/type-equivalence.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/unreached-invalid.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/function-references/unreached-valid.wast', async function () { await file(this.name, { spectest }) })

t.todo('/test/official/proposals/gc/array_copy.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/array_fill.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/array_init_data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/array_init_elem.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/array.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/binary-gc.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/binary.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/br_on_cast_fail.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/br_on_cast.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/br_on_non_null.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/br_on_null.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/br_table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/call_ref.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/data.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/elem.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/extern.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/func.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/global.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/i31.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/if.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/linking.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/local_get.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/local_init.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/local_tee.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/ref_as_non_null.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/ref_cast.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/ref_eq.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/ref_is_null.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/ref_null.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/ref_test.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/return_call_indirect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/return_call_ref.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/return_call.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/select.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/struct.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/table-sub.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/table.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/type-canon.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/type-equivalence.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/type-rec.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/gc/type-subtyping.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/unreached-invalid.wast', async function () { await file(this.name, { spectest }) })
t.todo('/test/official/proposals/gc/unreached-valid.wast', async function () { await file(this.name, { spectest }) })

t.todo('/test/official/proposals/multi-memory/address0.wast', async function () { await file(this.name, { spectest }) })

t.mute('/test/official/proposals/relaxed-simd/i8x16_relaxed_swizzle.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/relaxed-simd/i16x8_relaxed_q15mulr_s.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/relaxed-simd/i32x4_relaxed_trunc.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/relaxed-simd/relaxed_dot_product.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/relaxed-simd/relaxed_laneselect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/relaxed-simd/relaxed_madd_nmadd.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/relaxed-simd/relaxed_min_max.wast', async function () { await file(this.name, { spectest }) })

t.mute('/test/official/proposals/tail-call/return_call_indirect.wast', async function () { await file(this.name, { spectest }) })
t.mute('/test/official/proposals/tail-call/return_call.wast', async function () { await file(this.name, { spectest }) })

t.todo('/test/official/proposals/wide-arithmetic/wide-arithmetic.wast', async function () { await file(this.name, { spectest }) })
